export const foodItemsData = [
    {
        itemImage: "./images/freshly-baked-ciabatta.jpg",
        alt: "Ciabatta",
        itemName: "Freshly Baked Bread - Ciabatta",
        itemDescription: "Only the best stoneground flour, with no chemicals or preservatives. This ciabatta is made with traditional poolish starter and is fermented overnight, resulting in the characteristic large holes and succulent crumb. ",
        itemPrice: 3.00,
        id: "#1",
    },
    {
        itemImage: "./images/sourdough.jpg",
        alt: "Sourdough",
        itemName: "Freshly Baked Bread - Sourdough",
        itemDescription: "Naturally fermented sourdough is used to leaven the bread, which not only enhances the taste, but also adds to the nutritional value.",
        itemPrice: 3.20,
        id: "#2",
    },
    {
        itemImage: "./images/freshly-baked-rosemary.jpg",
        alt: "Rosemary & Sea Salt Fougasse",
        itemName: "Rosemary & Sea Salt Fougasse",
        itemDescription: "Enjoy our version of this Provençal bread. Its shape resembles an ear of wheat and the bread is baked on a hot stone in the oven.",
        itemPrice: 3.80,
        id: "#3",
    },
    {
        itemImage: "./images/seed-loaf.jpg",
        alt: "Seed Loaf",
        itemName: "Freshly Baked Bread - Seed Loaf",
        itemDescription: "This seeded loaf is made with rolled oats, sunflower seeds, linseed and whole almonds to provide you with incredible nutritional benefits.",
        itemPrice: 6.50,
        id: "#4",
    },
    {
        itemImage: "./images/freshly-baked-croissants.jpg",
        alt: "Croissants",
        itemName: "Freshly Baked Croissants - Pack of 4",
        itemDescription: "Made in the traditional way by preparing the dough and gradually rolling in butter into layers over a two-day period. A lot of care and technique goes into preparing these croissants, resulting in a deliciously flaky, light and airy pastry.",
        itemPrice: 4.50,
        id: "#5",
    },
    {
        itemImage: "./images/apple-twist.jpg",
        alt: "Apple Twist",
        itemName: "Apple Twist",
        itemDescription: "Our bakers use crispy apples, the best stoneground flour, with no chemicals or preservatives, and real butter to bake our Danish Twist.",
        itemPrice: 2.00,
        id: "#6",
    },
    {
        itemImage: "./images/bacon-aspargus-pastry.jpg",
        alt: "Bacon Aspargus Pastry",
        itemName: "Bacon Aspargus Pastry",
        itemDescription: "These pastries are made with a croissant base in the traditional way. Our bakers then use fresh asparagus spears from our garden, and gruyere cheese and place it in the centre of the pastry before gently folding and baking it to perfection.",
        itemPrice: 2.50,
        id: "#7",
    },
    {
        itemImage: "./images/choc-nut-caramel.jpg",
        alt: "Choc Nut Croissant",
        itemName: "Choc-Nut & Caramel Croissant",
        itemDescription: "Filled with a decadent chocolate-nut and caramel spread and topped with a light dusting of confectioner's sugar, these croissants are a delicious tea time treat.",
        itemPrice: 2.00,
        id: "#8",
    },
]
