export const foodItemsData = [
    {
        itemImage: "./images/freshly-baked-ciabatta.jpg",
        alt: "Ciabatta",
        itemName: "Freshly Baked Bread - Ciabatta",
        itemDescription: "Our ciabatta bread is light, airy, and perfect for sandwiches, paninis, or even as a side to your favorite pasta dish. With a crispy crust and a soft interior, our ciabatta is sure to satisfy your taste buds.",
        itemPrice: 3.00,
        id: "#1",
    },
    {
        itemImage: "./images/sourdough.jpg",
        alt: "Sourdough",
        itemName: "Freshly Baked Bread - Sourdough",
        itemDescription: "Freshly baked sourdough bread for sale! Made with a delicious combination of sourdough starter, flour, and water. Our bread is crusty on the outside and soft on the inside, with a tangy flavor that will leave you wanting more. ",
        itemPrice: 3.20,
        id: "#2",
    },
    {
        itemImage: "./images/freshly-baked-rosemary.jpg",
        alt: "Rosemary & Sea Salt Fougasse",
        itemName: "Rosemary & Sea Salt Fougasse",
        itemDescription: "Our artisanal fougasse is perfect as an appetizer or accompaniment to any meal. Each loaf is handcrafted, creating a unique shape that adds to its rustic charm. The crunchy crust and soft crumb make this bread a delight to eat.",
        itemPrice: 3.80,
        id: "#3",
    },
    {
        itemImage: "./images/seed-loaf.jpg",
        alt: "Seed Loaf",
        itemName: "Freshly Baked Bread - Seed Loaf",
        itemDescription: "Our seed loaf is made with a blend of flours and packed with a variety of seeds such as sunflower, pumpkin, it is a great source of fiber, protein, and healthy fats. Its nutty flavor and hearty texture make it perfect for toasting and topping with your favorite spreads or using as a base for a sandwich.",
        itemPrice: 6.50,
        id: "#4",
    },
    {
        itemImage: "./images/freshly-baked-croissants.jpg",
        alt: "Croissants",
        itemName: "Freshly Baked Croissants - Pack of 4",
        itemDescription: "Our croissants are made using a traditional French recipe to ensure an authentic taste and texture. Each croissant is carefully rolled and shaped by hand before being baked to golden perfection, creating a light and flaky pastry that melts in your mouth.",
        itemPrice: 4.50,
        id: "#5",
    },
    {
        itemImage: "./images/apple-twist.jpg",
        alt: "Apple Twist",
        itemName: "Apple Twist",
        itemDescription: "Made with a flaky, buttery pastry dough twisted around a sweet apple filling that's infused with cinnamon and spices, our apple twist is a delightful treat for any occasion. Each twist is baked to perfection, resulting in a golden, crispy exterior and a warm, gooey center. ",
        itemPrice: 2.00,
        id: "#6",
    },
    {
        itemImage: "./images/bacon-aspargus-pastry.jpg",
        alt: "Bacon Aspargus Pastry",
        itemName: "Bacon Aspargus Pastry",
        itemDescription: "Made with a crispy, flaky pastry dough, this delicious pastry is filled with a savory blend of chopped bacon, tender asparagus, and creamy cheese. Baked to perfection, our Bacon Asparagus Pastry boasts a golden-brown exterior and a rich, flavorful filling that's sure to please.",
        itemPrice: 2.50,
        id: "#7",
    },
    {
        itemImage: "./images/choc-nut-caramel.jpg",
        alt: "Choc Nut Croissant",
        itemName: "Choc-Nut & Caramel Croissant",
        itemDescription: "Made with our traditional croissant dough, this pastry is filled with a rich, gooey caramel and chocolate-nut filling. Baked to perfection, our croissant is crispy on the outside and buttery on the inside, with a delicious filling that oozes out with each bite. ",
        itemPrice: 2.00,
        id: "#8",
    },
]
